//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesCharts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductC
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Demand { get; set; }
        public int Supply { get; set; }
        public double Income { get; set; }
        public double Profit { get; set; }
        public double Provision { get; set; }
        public double DeliveryPayment { get; set; }
    }
}
